### PR TITLE
Easy save image on pc

### PR DESCRIPTION
**Pull request by vineetvk01**
Images from instagram api are received as jpg.

Steps to download :
1. Right click on any image (.jpg/.jpeg) file.
2. Click on 'Save image as...'
3. Select the path to save.

Closes: #1225

Preview: 

save-image

### CODE REVIEW

**Comment by ifedapoolarewaju** [comment]
Great work @vineetvk01! Thank you for this! I'm curious though, did you also consider the [html download attribute](https://www.w3schools.com/tags/att_a_download.asp)? It might be an easier approach, and it may also save us the hassle of maintaining the full implementation.

**Comment by vineetvk01** [comment]
_download_ attribute will workout with **<a>** tag. So, I was not sure of adding that as **MenuItem**. 
I'll try that option too and update.

**Comment by vineetvk01** [comment]
save-image-buton

**Comment by vineetvk01** [comment]
Hey @ifedapoolarewaju ! Please review the changes. 

Steps to download :
a. Right click on any image (.jpg/.jpeg) file.
b. Click on 'Save image as...'
c. Select the path to save.

**Comment by ifedapoolarewaju** [comment]
this looks great Thank you! 💪

**Pull request merged**
